config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :records
  resources :devices
  post '/devices/:id', to: 'devices#loan'
  resources :departments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  root 'sessions#new'
  resources :users

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :destroy]
  
  def index
    @departments = Department.all
  end
  
  def show
    @department = Department.find(params[:id])
    @department.id == 1 ? (@users = User.all) : (@users = User.where(department_id: @department.id))
  end
  
  def new
    @department = Department.new
  end
  
  def edit
    @department = Department.find(params[:id])
  end
  
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
  
    def admin_user
      redirect_to(root_url) unless user_permission_id?(current_user)
    end
    
    def department_params
      params.require(:department).permit(:name, :coding, :parent)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department, :html => { :class => "form-horizontal department" } do |f| %>

  <% if @department.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @department.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :coding, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coding, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :parent, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :parent, :class => 'form-control' %>
    </div>
  </div>
<br />
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                departments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/departments/edit.html.erb
<%- model_class = Department -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/departments/index.html.erb
<%- model_class = Department -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:coding) %></th>
      <th><%= model_class.human_attribute_name(:parent) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if user_permission_id?(current_user) && !current_user?(@user) %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= link_to department.id, department_path(department) %></td>
        <td><%= department.name %></td>
        <td><%= department.coding %></td>
        <td><%= department.parent %></td>
        <td><%= department.created_at.to_s.delete "UTC" %></td>
        <td>
          <% if user_permission_id?(current_user) && !current_user?(@user) %>
            <%= link_to 'Edit', edit_department_path(department) %> |
            <%= link_to 'Destroy', department_path(department),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_permission_id?(current_user) && !current_user?(@user) %>
  <%= link_to 'New department', new_department_path %>
<% end %>

app/views/departments/new.html.erb
<%- model_class = Department -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/departments/show.html.erb
<%- model_class = Department -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @department.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coding) %>:</strong></dt>
  <dd><%= @department.coding %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parent) %>:</strong></dt>
  <dd><%= @department.parent %></dd>
</dl>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:coding) %></th>
    <th><%= model_class.human_attribute_name(:department_id) %></th>
    <th><%= model_class.human_attribute_name(:role) %></th>
    <th><%= model_class.human_attribute_name(:sex) %></th>
    <th><%= model_class.human_attribute_name(:age) %></th>
    <th><%= model_class.human_attribute_name(:phone) %></th>
    <th><%= model_class.human_attribute_name(:email) %></th>
    <th><%= model_class.human_attribute_name(:state) %></th>
    <% if user_permission_id?(current_user) && !current_user?(@user) %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.id, user_path(user) %></td>
      <td><%= user.name %></td>
      <td><%= user.coding %></td>
      <td><%= user.department_id %></td>
      <td><%= user.role %></td>
      <td><%= user.sex %></td>
      <td><%= user.age %></td>
      <td><%= user.phone %></td>
      <td><%= user.email %></td>
      <td><%= user.state %></td>
      <td>
        <% if user_permission_id?(current_user) or current_user?(@user) %>
          <%= link_to 'Edit', edit_user_path(user) %> |
        <% end %>
        <% if user_permission_id?(current_user) && !current_user?(@user) %>
          <%= link_to 'Destroy', user_path(user),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', departments_path %>