config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :records
  resources :devices
  post '/devices/:id', to: 'devices#loan'
  resources :departments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  root 'sessions#new'
  resources :users

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :device, required: false
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :destroy]

  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def edit
    @record = Record.find(params[:id])
  end

  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def admin_user
      redirect_to(root_url) unless user_permission_id?(current_user)
    end

    def record_params
      params.require(:record).permit(:serial_num, :borrower, :loan_date, :return_date)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :serial_num %>
    <%= form.text_field :serial_num, id: :record_serial_num %>
  </div>

  <div class="field">
    <%= form.label :borrower %>
    <%= form.text_field :borrower, id: :record_borrower %>
  </div>

  <div class="field">
    <%= form.label :loan_date %>
    <%= form.date_select :loan_date, id: :record_loan_date %>
  </div>

  <div class="field">
    <%= form.label :return_date %>
    <%= form.date_select :return_date, id: :record_return_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Serial_num</th>
      <th>Borrower</th>
      <th>Loan_date</th>
      <th>Return_date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.serial_num %></td>
        <td><%= record.borrower %></td>
        <td><%= record.loan_date %></td>
        <td><%= record.return_date %></td>
        <% if user_permission_id?(current_user) && !current_user?(@user) %>
          <td><%= link_to 'Edit', edit_record_path(record) %></td>
          <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_permission_id?(current_user) && !current_user?(@user) %>
  <%= link_to 'New Record', new_record_path %>
<% end %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>