config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :records
  resources :devices
  post '/devices/:id', to: 'devices#loan'
  resources :departments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  root 'sessions#new'
  resources :users

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "个人", user_path(@current_user) %></li>
          <li><%= link_to "部门", departments_path %></li>
          <li><%= link_to "办公用品", devices_path %></li>
          <li><%= link_to "借用记录", records_path %></li>
          <li><%= link_to "所有人", users_path %></li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManageSystem</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
	<%= javascript_include_tag "application" %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">

	<%= yield %>

</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</body>
</html>